### ISSUE TITLE
When using monkey blur and SBA Entity Outline, entities are invisible

### ISSUE THREAD

**Issue by Wyvest** [Polyfrost/PolyBlur#2]
> When using monkey blur and SBA Entity Outline, entities are invisible. Its only monkey blur which is the best one and I would prefer to be able to use it when playing skyblock
>
> ![image](https://user-images.githubusercontent.com/45589059/206014937-64461ca1-9f83-455d-8426-26359048949a.png)

(from Goatted ticket 154)

**Comment by hoodieabe** [comment]
same issue, did you get a fix?

**Comment by Kathund** [comment]
SkyHanni Glowing dropped items causing the issue

**Comment by Wyvest** [comment]
@hoodieabe @Kathund Fixed in the latest release (v1.0.1)
